const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{background_terrain: 0},
	{terrain_dirt_top_a: 0},
	{seaweed_green_a: 0},
	{seaweed_pink_a: 0},
	{rock_a: 0},
	{rock_a2: 0},
	{fish_blue_skeleton_outline: 0},
	{fish_orange_skeleton_outline: 0},
	{bubble_a: 0},
	{Platform: 0},
	{fish_blue_outline: 0},
	{scored: 0},
	{rock_b_jos: 0},
	{rock_b_sus: 0},
	{Text: 0},
	{Touch: 0},
	{Keyboard: 0},
	{button_rectangle_depth_gradient: 0},
	{Text2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Text3: 0},
	{download: 0},
	{hdriunderwateroceanpanoramas: 0},
	{e7915f5c2ae61a10c0e4665ac81add: 0},
	{secondsPerObstacle: 0},
	{Jump: 0},
	{ScrollSpeed: 0},
	{Score: 0}
];

self.InstanceType = {
	background_terrain: class extends self.ISpriteInstance {},
	terrain_dirt_top_a: class extends self.ISpriteInstance {},
	seaweed_green_a: class extends self.ISpriteInstance {},
	seaweed_pink_a: class extends self.ISpriteInstance {},
	rock_a: class extends self.ISpriteInstance {},
	rock_a2: class extends self.ISpriteInstance {},
	fish_blue_skeleton_outline: class extends self.ISpriteInstance {},
	fish_orange_skeleton_outline: class extends self.ISpriteInstance {},
	bubble_a: class extends self.ISpriteInstance {},
	fish_blue_outline: class extends self.ISpriteInstance {},
	rock_b_jos: class extends self.ISpriteInstance {},
	rock_b_sus: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	button_rectangle_depth_gradient: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	download: class extends self.ISpriteInstance {},
	hdriunderwateroceanpanoramas: class extends self.ISpriteInstance {},
	e7915f5c2ae61a10c0e4665ac81add: class extends self.ISpriteInstance {}
}